package com.altieri.starling.di

object DIConst {
    const val APP_BASE_URL = "APP_BASE_URL"
    const val BOOLEAN_FEED = "BOOLEAN_FEED"
    const val STRING_FEED = "STRING_FEED"
    const val SINGLE_THREAD_DISPATCHER = "SINGLE_THREAD_DISPATCHER"
    const val TOKEN_REPOSITORY_DISPATCHER = "TOKEN_REPOSITORY_DISPATCHER"
    const val DEFAULT_DISPATCHER = "DEFAULT_DISPATCHER"

    const val ACCOUNTS_STATE_FEED = "ACCOUNT_STATE_FEED"
    const val ACCOUNTS_GOAL_STATE_FEED = "ACCOUNTS_GOAL_STATE_FEED"
    const val TRANSACTIONS_STATE_FEED = "TRANSACTIONS_STATE_FEED"
}
